model:
    name: 'RidgeRULPredictor'
    alpha: 1.0
train_test_split:
    name: 'CellIdPrefixTrainTestSplitter'
    cell_data_path:
        - 'data/processed/CALCE'
        - 'data/processed/MY_POUCH'
    test_prefixes:
        - 'RPT_'
feature:
    name: 'NormalizedVoltageCapacityMatrixFeatureExtractor'
    interp_dim: 256
    baseline_cycle_number: 0
    cycles_to_compare:
        - 100
        - 200
    min_voltage_in_V: 2.7
    max_voltage_in_V: 4.2
    discharge_current_sign: 'auto'
    allow_nearest_cycle: True
    max_cycle_number_gap: 2
    append_soh_scalar: True
label:
    name: 'SOHAtCycleNumberLabelAnnotator'
    cycle_number: 600
    baseline_cycle_number: 0
    mode: 'relative'
    allow_nearest_cycle: True
    max_cycle_number_gap: 2
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'ZScoreDataTransformation'
