model:
    name: 'RidgeRULPredictor'
    alpha: 1.0

train_test_split:
    name: 'RandomTrainTestSplitter'
    cell_data_path: 'data/processed/MSAS'
    seed: 2
    train_test_split_ratio: 0.8

feature:
    name: 'EFCNormalizedVoltageCapacityMatrixFeatureExtractor'
    interp_dim: 50
    baseline_efc: 0.0
    efc_checkpoints:
        - 100.0
        - 200.0
        - 300.0
    min_voltage_in_V: 2.5
    max_voltage_in_V: 4.09
    max_abs_efc_error: 400.0
    allowed_tags:
        - ET_T23
        - CU
        - exCU
        - AT_T23
    append_soh_scalar: True
    include_shape_delta: True
    include_cv: False
    cc_current_fraction: 0.98
    cv_voltage_window_in_V: 0.05

label:
    name: 'KneeBeforeEFCLabelAnnotator'
    threshold_efc: 600.0
    baseline_efc: 0.0
    max_abs_efc_error: 400.0
    allowed_tags:
        - ET_T23
        - CU
        - exCU
        - AT_T23
    include_cv: False
    cc_current_fraction: 0.98
    cv_voltage_window_in_V: 0.05
    min_points: 3
    min_slope_drop: 1e-5
    allow_baseline_fallback: True
    monotonic: True
    no_knee_as_negative_if_max_efc_ge_threshold: True

feature_transformation:
    name: 'ZScoreDataTransformation'

label_transformation:
    name: 'SequentialDataTransformation'
    transformations: []
