model:
    name: 'XGBoostRULPredictor'
    n_estimators: 500
    max_depth: 6
    learning_rate: 0.05
    subsample: 0.9
    colsample_bytree: 0.9
    reg_lambda: 1.0
train_test_split:
    name: 'RandomTrainTestSplitter'
    cell_data_path: 'data/processed/RWTH'
    seed: 0
    train_test_split_ratio: 0.8
feature:
    name: 'NormalizedVoltageCapacityMatrixFeatureExtractor'
    interp_dim: 256
    baseline_cycle_number: 0
    cycles_to_compare:
        - 100
        - 200
    min_voltage_in_V: 3.5
    max_voltage_in_V: 3.9
    discharge_current_sign: 'auto'
    allow_nearest_cycle: True
    max_cycle_number_gap: 2
    append_soh_scalar: True
label:
    name: 'SOHAtCycleNumberLabelAnnotator'
    cycle_number: 600
    baseline_cycle_number: 0
    mode: 'relative'
    allow_nearest_cycle: True
    max_cycle_number_gap: 2
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'ZScoreDataTransformation'
