model:
    name: 'RidgeRULPredictor'
    alpha: 1.0
train_test_split:
    name: 'RandomTrainTestSplitter'
    cell_data_path: 'data/processed/CALCE'
    seed: 0
    train_test_split_ratio: 0.8
feature:
    name: 'NormalizedVoltageCapacityMatrixFeatureExtractor'
    interp_dim: 256
    baseline_cycle_number: 0
    cycles_to_compare:
        - 100
        - 200
    min_voltage_in_V: 2.7
    max_voltage_in_V: 4.2
    discharge_current_sign: 'auto'
    allow_nearest_cycle: True
    max_cycle_number_gap: 2
    append_soh_scalar: True
label:
    name: 'RULLabelAnnotator'
    eol_soh: 0.8
    pad_eol: True
    min_rul_limit: 100.0
feature_transformation:
    name: 'ZScoreDataTransformation'
label_transformation:
    name: 'SequentialDataTransformation'
    transformations:
        - name: 'LogScaleDataTransformation'
        - name: 'ZScoreDataTransformation'
